name: Sonar and GitHub Actions Pipeline

on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build application
        run: yarn build
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build/
  
